### ISSUE TITLE
Please decide on the license.

### ISSUE THREAD

**Issue by fujisanx** [Telosnex/fllama#3]
I would greatly appreciate it if you could clarify the licensing terms.

**Comment by jpohhhh** [comment]
Added! Thanks for pointing that out, I thought I did already

TL;DR: Dual license, GPLv2 and commercial. 

GPLv2 requires sharing code of the app that integrates the library. 

Thus, people using FLLAMA for-profit will desire a commercial license.

The commercial license is _not_ to make money off people starting a new app, but rather, to prevent a case where 2 years from now, this is at the core of another app making a ton of money. 

Apologies for delay: I didn't get a GitHub email for some reason
